// AI application engineering English: lessons 1–10.
// Word format: [term, American IPA, Chinese meaning, example, pronunciation tip].
window.LESSONS_A = [
  {
    id: 1, week: 1, title: "模型与提示词", subtitle: "能用英语说明模型如何根据指令生成回答。",
    words: [
      ["model", "/ˈmɑːdəl/", "模型", "This model can summarize long documents.", "重音在第一个音节，读 MAH-dl。"],
      ["prompt", "/prɑːmpt/", "提示词；指令", "Write a clear prompt for the assistant.", "词尾 /mpt/ 连起来收住，不加尾音。"],
      ["token", "/ˈtoʊkən/", "词元；模型处理文本的单位", "A long prompt uses more tokens.", "前半像 toe，重音在前。"],
      ["context", "/ˈkɑːntekst/", "上下文", "The model needs enough context.", "重音在 CON，词尾 /kst/ 要收紧。"],
      ["generate", "/ˈdʒenəreɪt/", "生成", "The system generates a useful answer.", "开头 /dʒ/ 像 judge，重音在 GEN。"],
      ["instruction", "/ɪnˈstrʌkʃən/", "指令；说明", "Follow the user's instructions.", "重音在 STRUC，词尾是 /ʃən/。"],
      ["output", "/ˈaʊtpʊt/", "输出；输出内容", "The output should be short and clear.", "重音在 OUT，/aʊ/ 如 out。"],
      ["summarize", "/ˈsʌməraɪz/", "总结；概括", "Please summarize this report.", "重音在 SUM，词尾读 /raɪz/。"],
      ["hallucination", "/həˌluːsəˈneɪʃən/", "幻觉；模型编造内容", "We check the answer for hallucinations.", "主要重音在 NAY，别把词尾读成 tion。"],
      ["temperature", "/ˈtempərətʃər/", "温度参数；控制输出随机性", "Lower the temperature for a steadier answer.", "重音在 TEM，末尾近似 chər。"],
    ],
    sentences: [
      {text: "The model uses the prompt and context to generate an answer.", translation: "模型利用提示词和上下文生成答案。"},
      {text: "Please make the output shorter and follow these instructions.", translation: "请缩短输出，并遵循这些指令。"},
      {text: "We review important answers because the model can hallucinate.", translation: "我们会检查重要回答，因为模型可能编造内容。"},
    ],
  },
  {
    id: 2, week: 1, title: "向量与检索", subtitle: "能描述用户提问后如何找到相关资料。",
    words: [
      ["embedding", "/ɪmˈbedɪŋ/", "嵌入向量", "We create an embedding for each passage.", "重音在 BED，不在开头。"],
      ["retrieve", "/rɪˈtriːv/", "检索；取回", "The app retrieves relevant passages.", "重音在 TRIEVE，/iː/ 拉长。"],
      ["vector", "/ˈvektər/", "向量", "The database stores vectors.", "重音在 VEC，词尾弱读 /tər/。"],
      ["relevant", "/ˈreləvənt/", "相关的", "Return only relevant results.", "重音在 REL，不读成 re-LAY。"],
      ["query", "/ˈkwɪri/", "查询；问题", "The user sends a query.", "开头 /kw/ 连读，重音在前。"],
      ["similarity", "/ˌsɪməˈlærəti/", "相似度", "Similarity helps us find related text.", "主要重音在 LAR。"],
      ["chunk", "/tʃʌŋk/", "文本块；分块", "Split the file into small chunks.", "开头 /tʃ/ 像 chair，词尾 /ŋk/ 收住。"],
      ["document", "/ˈdɑːkjəmənt/", "文档", "This document contains the policy.", "重音在 DOC；这里作名词。"],
      ["passage", "/ˈpæsɪdʒ/", "段落；片段", "The top passage answers the question.", "重音在 PASS，结尾 /dʒ/。"],
      ["rank", "/ræŋk/", "排序；名次", "Rank the results by relevance.", "元音 /æ/ 张大口，词尾 /ŋk/ 收住。"],
    ],
    sentences: [
      {text: "The system retrieves relevant documents for the user's query.", translation: "系统根据用户查询检索相关文档。"},
      {text: "We split each document into chunks before creating embeddings.", translation: "我们先把每份文档分块，再创建嵌入向量。"},
      {text: "The search service ranks passages by similarity.", translation: "搜索服务按相似度对片段排序。"},
    ],
  },
  {
    id: 3, week: 1, title: "Agent 与工具", subtitle: "能说清智能体选择工具和执行步骤的过程。",
    words: [
      ["agent", "/ˈeɪdʒənt/", "智能体", "The agent can call external tools.", "开头 /eɪ/ 如 day，重音在前。"],
      ["workflow", "/ˈwɜːrkfloʊ/", "工作流", "This workflow has three steps.", "重音在 WORK，flow 读 /floʊ/。"],
      ["function", "/ˈfʌŋkʃən/", "函数；功能", "The model selects the right function.", "中间 /ŋkʃ/ 要连起来。"],
      ["response", "/rɪˈspɑːns/", "响应；回答", "Return a structured response.", "重音在 SPONSE。"],
      ["execute", "/ˈeksɪkjuːt/", "执行", "The server executes the task.", "重音在 EX，末尾 /kjuːt/。"],
      ["tool", "/tuːl/", "工具", "This tool looks up current data.", "单音节，/uː/ 拉长。"],
      ["plan", "/plæn/", "计划；规划", "The agent makes a short plan.", "元音 /æ/ 张大口。"],
      ["action", "/ˈækʃən/", "操作；行动", "Ask before taking a risky action.", "重音在 AC，词尾 /ʃən/。"],
      ["result", "/rɪˈzʌlt/", "结果", "Check the result before continuing.", "重音在 SULT，/z/ 要发声。"],
      ["iterate", "/ˈɪtəreɪt/", "迭代；重复改进", "We iterate after each test.", "重音在 IT，结尾 /reɪt/。"],
    ],
    sentences: [
      {text: "The agent selects a tool and executes the next step.", translation: "智能体选择工具并执行下一步。"},
      {text: "The workflow checks each result before taking another action.", translation: "工作流在执行下一项操作前检查每个结果。"},
      {text: "We iterate on the plan when a tool returns an error.", translation: "工具返回错误时，我们会调整计划。"},
    ],
  },
  {
    id: 4, week: 1, title: "API 请求", subtitle: "能解释客户端、请求、参数和错误。",
    words: [
      ["endpoint", "/ˈendpɔɪnt/", "API 端点", "Send the request to this endpoint.", "END-point 两部分连读，重音在前。"],
      ["request", "/rɪˈkwest/", "请求", "The client sends an HTTP request.", "名词和动词均重读 QUEST。"],
      ["parameter", "/pəˈræmɪtər/", "参数", "This parameter is optional.", "重音在 RAM。"],
      ["validate", "/ˈvælɪdeɪt/", "验证", "Validate the input before processing.", "重音在 VAL，/æ/ 张大口。"],
      ["latency", "/ˈleɪtənsi/", "延迟", "Caching can reduce latency.", "重音在 LAY。"],
      ["client", "/ˈklaɪənt/", "客户端", "The client sends a JSON body.", "首音节 /klaɪ/ 如 climb 的开头。"],
      ["server", "/ˈsɜːrvər/", "服务器", "The server returns a response.", "重音在 SER，/ɜːr/ 卷舌。"],
      ["payload", "/ˈpeɪloʊd/", "请求或响应中传送的数据", "The payload contains the user's question.", "重音在 PAY，load 读 /loʊd/。"],
      ["status", "/ˈstætəs/", "状态；状态码", "Check the status code first.", "重音在 STA，/æ/ 张大口。"],
      ["error", "/ˈerər/", "错误", "Log the error for debugging.", "重音在 AIR，末尾轻读。"],
    ],
    sentences: [
      {text: "The API validates each request before returning a response.", translation: "API 在返回响应前验证每个请求。"},
      {text: "The client sends a JSON payload to the endpoint.", translation: "客户端把 JSON 数据发送到该端点。"},
      {text: "Check the status code when the server returns an error.", translation: "服务器返回错误时，请检查状态码。"},
    ],
  },
  {
    id: 5, week: 1, title: "FastAPI 开发", subtitle: "能用英语介绍常见的 FastAPI 项目结构。",
    words: [
      ["framework", "/ˈfreɪmwɜːrk/", "框架", "FastAPI is a Python web framework.", "重音在 FRAME，work 的 /ɜːr/ 卷舌。"],
      ["route", "/ruːt/", "路由；路径处理", "Add a route for the chat endpoint.", "这里读 /ruːt/；美式也可读 /raʊt/。"],
      ["schema", "/ˈskiːmə/", "数据结构定义", "The schema describes the response.", "开头读 /sk/，不是 sh。"],
      ["field", "/fiːld/", "字段", "The name field is required.", "/iː/ 拉长，词尾 /ld/ 收住。"],
      ["type", "/taɪp/", "类型", "Set the field type to string.", "单音节 /taɪp/，词尾 /p/ 不加元音。"],
      ["dependency", "/dɪˈpendənsi/", "依赖项；依赖注入项", "Use a dependency to check access.", "重音在 PEN，结尾 /dənsi/。"],
      ["middleware", "/ˈmɪdəlwer/", "中间件", "Middleware logs each request.", "重音在 MID，末尾 ware 如 wear。"],
      ["documentation", "/ˌdɑːkjəmenˈteɪʃən/", "文档", "Open the API documentation in a browser.", "主要重音在 TAY，词尾 /ʃən/。"],
      ["async", "/eɪˈsɪŋk/", "异步的；异步函数", "This async function waits for the API.", "常读 AY-SINK，重音在 SINK。"],
      ["handler", "/ˈhændlər/", "处理函数", "The handler returns a JSON response.", "重音在 HAND，/æ/ 张大口。"],
    ],
    sentences: [
      {text: "This FastAPI route accepts a question and returns an answer.", translation: "这条 FastAPI 路由接收问题并返回答案。"},
      {text: "The schema defines the fields in the request body.", translation: "这个数据结构定义了请求体中的字段。"},
      {text: "We use a dependency to check the user's access before the handler runs.", translation: "处理函数运行前，我们用依赖项检查用户权限。"},
    ],
  },
  {
    id: 6, week: 2, title: "提示词设计", subtitle: "能编写清晰的角色、约束和输出格式说明。",
    words: [
      ["role", "/roʊl/", "角色", "Give the assistant a clear role.", "单音节，/oʊ/ 如 go。"],
      ["system", "/ˈsɪstəm/", "系统；系统消息", "The system message sets the rules.", "重音在 SYS，末尾弱读。"],
      ["example", "/ɪɡˈzæmpəl/", "示例", "Add an example to show the format.", "重音在 ZAM，开头常读 /ɪɡ/。"],
      ["constraint", "/kənˈstreɪnt/", "约束条件", "State the constraints in the prompt.", "重音在 STRAINT，词尾 /nt/ 收住。"],
      ["format", "/ˈfɔːrmæt/", "格式；格式化", "Use JSON as the output format.", "作名词时重音在 FOR。"],
      ["objective", "/əbˈdʒektɪv/", "目标", "Explain the objective in one sentence.", "重音在 JEC，词尾 /tɪv/。"],
      ["clarify", "/ˈklærəfaɪ/", "澄清", "Ask a question to clarify the task.", "重音在 CLAR，结尾 /faɪ/。"],
      ["revise", "/rɪˈvaɪz/", "修改；修订", "Revise the prompt after testing it.", "重音在 VISE，词尾 /z/ 发声。"],
      ["evaluate", "/ɪˈvæljueɪt/", "评估", "Evaluate the answer against the rules.", "重音在 VAL，结尾 /eɪt/。"],
      ["template", "/ˈtemplət/", "模板", "Reuse this template for reports.", "重音在 TEM，末尾轻读 /lət/。"],
    ],
    sentences: [
      {text: "Give the assistant a role, a clear objective, and a short example.", translation: "给助手指定角色、明确目标，并提供一个简短示例。"},
      {text: "The prompt requires a JSON response with three fields.", translation: "这条提示词要求返回包含三个字段的 JSON。"},
      {text: "If the answer is unclear, revise the instructions and test again.", translation: "如果回答不清楚，就修改指令并重新测试。"},
    ],
  },
  {
    id: 7, week: 2, title: "资料导入", subtitle: "能描述把原始文件处理成可检索内容的步骤。",
    words: [
      ["source", "/sɔːrs/", "来源；数据源", "Record the source of each file.", "单音节，/ɔːr/ 卷舌。"],
      ["extract", "/ɪkˈstrækt/", "提取", "Extract text from the PDF.", "这里作动词，重音在 TRACT。"],
      ["parse", "/pɑːrs/", "解析", "Parse the file before indexing it.", "/ɑːr/ 卷舌，结尾 /s/。"],
      ["clean", "/kliːn/", "清洗；清理", "Clean the text before splitting it.", "/iː/ 拉长，词尾 /n/。"],
      ["metadata", "/ˈmetəˌdeɪtə/", "元数据", "Save the title as metadata.", "META 重读；data 也可读 /ˈdætə/。"],
      ["duplicate", "/ˈduːplɪkət/", "重复的；重复项", "Remove duplicate files.", "这里作形容词，重音在 DU。"],
      ["split", "/splɪt/", "拆分", "Split the text into smaller parts.", "开头 /spl/ 连读，词尾 /t/ 收住。"],
      ["batch", "/bætʃ/", "批次；批量", "Process the files in batches.", "/æ/ 张大口，词尾 /tʃ/。"],
      ["pipeline", "/ˈpaɪplaɪn/", "处理流水线", "The pipeline cleans and indexes files.", "重音在 PIPE，line 读 /laɪn/。"],
      ["ingest", "/ɪnˈdʒest/", "导入并处理数据", "Ingest new documents every night.", "重音在 GEST，/dʒ/ 如 judge。"],
    ],
    sentences: [
      {text: "Our pipeline extracts text from PDFs and saves the source name.", translation: "我们的处理流程从 PDF 提取文本并保存来源名称。"},
      {text: "Clean the text and remove duplicates before creating chunks.", translation: "创建文本块之前，先清洗文本并删除重复内容。"},
      {text: "We ingest new documents in batches every evening.", translation: "我们每天晚上分批导入新文档。"},
    ],
  },
  {
    id: 8, week: 2, title: "RAG 问答流程", subtitle: "能解释检索增强生成中的证据、引用和兜底处理。",
    words: [
      ["retrieval", "/rɪˈtriːvəl/", "检索", "Retrieval happens before generation.", "重音在 TRIEV，/iː/ 拉长。"],
      ["augmented", "/ɔːɡˈmentɪd/", "增强的", "RAG means retrieval-augmented generation.", "重音在 MEN，首音节 /ɔːɡ/。"],
      ["generation", "/ˌdʒenəˈreɪʃən/", "生成", "Generation uses the retrieved text.", "主要重音在 RAY，词尾 /ʃən/。"],
      ["grounding", "/ˈɡraʊndɪŋ/", "基于证据作答", "Grounding keeps the answer tied to sources.", "重音在 GROUND，/aʊ/ 如 now。"],
      ["citation", "/saɪˈteɪʃən/", "引用；引文标记", "Add a citation for each claim.", "重音在 TAY，词尾 /ʃən/。"],
      ["evidence", "/ˈevədəns/", "证据", "The answer needs supporting evidence.", "重音在 EV，末尾 /dəns/。"],
      ["rerank", "/ˌriːˈræŋk/", "重新排序检索结果", "Rerank the top results before answering.", "re 读 /riː/；主要重音在 RANK。"],
      ["threshold", "/ˈθreʃhoʊld/", "阈值", "Set a threshold for low-quality matches.", "开头 /θ/ 咬舌，重音在 THRESH。"],
      ["fallback", "/ˈfɔːlbæk/", "兜底方案", "Use a fallback when no source matches.", "重音在 FALL，back 读 /bæk/。"],
      ["recall", "/ˈriːkɔːl/", "召回率；找回相关结果的能力", "Higher recall can find more relevant passages.", "这里作名词，重音在 RE。"],
    ],
    sentences: [
      {text: "RAG retrieves passages before the model generates an answer.", translation: "RAG 先检索段落，再让模型生成答案。"},
      {text: "A good answer includes evidence and a citation to the source.", translation: "好的回答会包含证据并引用来源。"},
      {text: "If no passage passes the threshold, use a fallback response.", translation: "如果没有片段达到阈值，就使用兜底回复。"},
    ],
  },
  {
    id: 9, week: 2, title: "向量数据库", subtitle: "能解释向量索引、距离、过滤和搜索分数。",
    words: [
      ["index", "/ˈɪndeks/", "索引；建立索引", "Build an index for the embeddings.", "重音在 IN，词尾 /deks/。"],
      ["dimension", "/dɪˈmenʃən/", "维度", "Each vector has the same dimension.", "重音在 MEN，词尾 /ʃən/。"],
      ["distance", "/ˈdɪstəns/", "距离", "The search compares vector distance.", "重音在 DIS，末尾 /təns/。"],
      ["cosine", "/ˈkoʊsaɪn/", "余弦", "Cosine similarity compares vector direction.", "首音节像 co，末尾 /saɪn/。"],
      ["nearest", "/ˈnɪrɪst/", "最近的", "Return the nearest five vectors.", "重音在 NEAR，/r/ 要卷舌。"],
      ["filter", "/ˈfɪltər/", "过滤；筛选", "Filter results by document type.", "重音在 FIL，末尾 /tər/。"],
      ["collection", "/kəˈlekʃən/", "集合；数据集合", "Store these vectors in one collection.", "重音在 LEC，结尾 /ʃən/。"],
      ["namespace", "/ˈneɪmspeɪs/", "命名空间；数据隔离区", "Use a separate namespace for each team.", "重音在 NAME，space 读 /speɪs/。"],
      ["score", "/skɔːr/", "得分", "Show the search score for each result.", "单音节，/ɔːr/ 卷舌。"],
      ["search", "/sɜːrtʃ/", "搜索；检索", "Search the collection for similar vectors.", "单音节，/ɜːr/ 卷舌，词尾 /tʃ/。"],
    ],
    sentences: [
      {text: "The vector database searches an index for the nearest matches.", translation: "向量数据库在索引中搜索最接近的匹配项。"},
      {text: "Filter the collection by team before showing the results.", translation: "显示结果前，先按团队筛选数据集合。"},
      {text: "A higher similarity score does not always mean the answer is correct.", translation: "相似度得分更高，不一定意味着答案正确。"},
    ],
  },
  {
    id: 10, week: 2, title: "MCP 与工具调用", subtitle: "能讲述 AI 应用如何发现和调用外部工具。",
    words: [
      ["protocol", "/ˈproʊtəkɔːl/", "协议", "MCP is a protocol for connecting AI apps to tools.", "重音在 PRO，词尾 /kɔːl/。"],
      ["host", "/hoʊst/", "宿主应用", "The host connects to an MCP server.", "单音节，/oʊ/ 如 go。"],
      ["resource", "/ˈriːsɔːrs/", "资源；可读取的内容", "The server exposes a document resource.", "这里读 REE-source；美式也有 /rɪˈsɔːrs/。"],
      ["capability", "/ˌkeɪpəˈbɪləti/", "能力；功能", "The client checks the server's capabilities.", "主要重音在 BIL。"],
      ["tool call", "/tuːl kɔːl/", "工具调用", "The app logs each tool call.", "两词各读清楚，call 的 /ɔː/ 拉开。"],
      ["argument", "/ˈɑːrɡjəmənt/", "参数；调用入参", "Pass the file name as an argument.", "重音在 AR，/ɡj/ 连起来。"],
      ["permission", "/pərˈmɪʃən/", "权限；许可", "Ask for permission before writing a file.", "重音在 MIS，结尾 /ʃən/。"],
      ["authorize", "/ˈɔːθəraɪz/", "授权", "Authorize the connection before use.", "开头 /ɔːθ/，/θ/ 要轻咬舌。"],
      ["connector", "/kəˈnektər/", "连接器", "The connector provides access to the calendar.", "重音在 NEC，末尾 /tər/。"],
      ["integration", "/ˌɪntəˈɡreɪʃən/", "集成", "Test the integration with one tool.", "主要重音在 GRAY，结尾 /ʃən/。"],
    ],
    sentences: [
      {text: "The host connects to an MCP server that exposes tools and resources.", translation: "宿主应用连接到提供工具和资源的 MCP 服务器。"},
      {text: "The client sends a tool call with the required arguments.", translation: "客户端发送工具调用，并附上所需参数。"},
      {text: "Ask for permission before a tool changes a user's files.", translation: "工具修改用户文件前，先请求许可。"},
    ],
  },
];
